version: 2.1

orbs:
  artifact-management: avvo/artifact-management@0.0.6

jobs:

  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - artifact-management/gem-build-and-push

workflows:
  version: 2.1
  build-workflow:
    jobs:
    - build:
        context: org-global
        filters:
          tags:
            only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
          branches:
            ignore: /.*/
